# Generated by Django 5.1.2 on 2024-11-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0002_userprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='phrase_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
