# Generated by Django 5.1.2 on 2024-11-27 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0003_alter_phrase_phrase_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phrase',
            unique_together={('lesson', 'phrase_number')},
        ),
    ]
