# Generated by Django 5.1.2 on 2024-11-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0004_alter_phrase_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
